version: "3"

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/srv
      - ./data:/data


  airflow_scheduler:
    build:
      context: ./app
    command: airflow scheduler
    volumes:
      - ./app:/srv

  airflow:
    build:
      context: ./app
    command: airflow webserver
    volumes:
      - ./app:/srv
      - ./data:/data
    ports:
      - "${AIRFLOW_PORT}:8080"

  front:
    build:
      context: ./front
    environment:
      - NODE_ENV=development
    command: npm run watch
    volumes:
      - ./front:/srv

  web:
    build:
      context: ./web

    volumes:
      - ./front/dist:/public/aplf
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - front
