version: "3"

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/srv
      - ./data:/data
  web:
    build:
      context: ./app

    volumes:
      - ./front/dist:/public
    ports:
      - "${WEB_PORT}:80"


  front:
    build:
      context: ./front
    environment:
      - NODE_ENV=development
    command: npm run watch
    volumes:
      - ./front:/srv
    depends_on:
      - web
