version: "3"
services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/srv
      - ./data:/data

  front:
    build:
      context: ./front
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "${WEBPACK_DEV_PORT}:9000"
    volumes:
      - ./front:/srv

