version: "3"
services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/srv
      - ./data:/data

  front:
    build:
      context: ./front
    environment:
      - NODE_ENV=development
      - WEBPACK_DEV_SERVER_PORT
    command: npm run dev
    ports:
      - "${WEBPACK_DEV_SERVER_PORT}:${WEBPACK_DEV_SERVER_PORT}"
    volumes:
      - ./front:/srv

