version: "3"

services:

  dask-scheduler:
    build:
      context: ./app
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    command: dask-scheduler
    volumes:
      - ./app:/srv
      - ./store:/store

  dask-worker:
    build:
      context: ./app
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    command: dask-worker dask-scheduler:8786 --local-directory=/dask-worker-space
    volumes:
      - ./app:/srv
      - ./store:/store
    depends_on:
      - dask-scheduler

  front:
    build:
      context: ./front
    environment:
      - NODE_ENV=development
    command: npm run watch
    volumes:
      - ./front:/srv

  web:
    build:
      context: ./web

    volumes:
      - ./front/dist:/public/aplf
      - ./store:/public/store
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - front
      - dask-scheduler

  notebook:
    build:
      context: ./app
    environment:
      - JUPYTER_CONFIG_DIR=/srv
    command: jupyter notebook
    volumes:
      - ./app:/srv
      - ./store:/store
    ports:
      - "${NOTEBOOK_PORT}:8888"

  app:
    build:
      context: ./app
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    volumes:
      - ./app:/srv
      - ./store:/store
    depends_on:
      - dask-worker
      - web


