version: "3"

services:
  dask-worker:
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    command: dask-worker ${DASKSCHEDULER_CONN} --local-directory=/dask-worker-space --nprocs=1  --nthreads=1 --memory-limit=40e8
    volumes:
      - ./app:/srv
      - ./store:/store
      - ./log:/log

