version: "3"
services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/srv
      - ./data:/data

  front:
    build:
      context: ./front
    environment:
      - NODE_ENV=development
    volumes:
      - ./front:/srv

