version: "3"

services:

  dask_scheduler:
    build:
      context: ./app
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    command: dask-scheduler
    volumes:
      - ./app:/srv
      - ./data:/data
    ports:
      - "8787:8787"

  dask_worker:
    build:
      context: ./app
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    command: dask-worker dask_scheduler:8786 --local-directory=/dask-worker-space
    volumes:
      - ./app:/srv
      - ./data:/data
    depends_on:
      - dask_scheduler

  app:
    build:
      context: ./app
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    volumes:
      - ./app:/srv
      - ./data:/data

  front:
    build:
      context: ./front
    environment:
      - NODE_ENV=development
    command: npm run watch
    volumes:
      - ./front:/srv

  web:
    build:
      context: ./web

    volumes:
      - ./front/dist:/public/aplf
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - front
