version: "3"

volumes:
  log:

services:

  tensorboard:
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    command: tensorboard --logdir=/log runs
    volumes:
      - ./app:/srv
      - ./store:/store
      - ./log:/log


  dask-scheduler:
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    command: dask-scheduler
    volumes:
      - ./app:/srv
      - ./store:/store
      - ./log:/log

  dask-worker:
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    command: dask-worker dask-scheduler:8786 --local-directory=/dask-worker-space
    volumes:
      - ./app:/srv
      - ./store:/store
      - ./log:/log
    depends_on:
      - dask-scheduler

  front:
    build:
      context: ./front
      args:
        - http_proxy
        - https_proxy
    environment:
      - NODE_ENV=development
    command: npm run watch
    volumes:
      - ./front:/srv

  web:
    build:
      context: ./web
      args:
        - http_proxy
        - https_proxy

    volumes:
      - ./front/dist:/public/aplf
      - ./store:/public/store
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - front
      - dask-scheduler
      - tensorboard

  app:
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    volumes:
      - ./app:/srv
      - ./store:/store
      - ~/.kaggle:/root/.kaggle
      - ./log:/log
    depends_on:
      - dask-worker
      - web


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
