version: "3"

volumes:
  mongo_data:

services:

  tensorboard:
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    command: tensorboard --logdir=/store/log
    volumes:
      - ./app:/srv
      - ./store:/store
    ports:
      - ${TENSORBOARD_PORT}:6006

  dask-scheduler:
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    command: dask-scheduler
    volumes:
      - ./app:/srv
      - ./store:/store
    ports:
      - ${DASKBOARD_PORT}:8787
      - ${DASKSCHEDULER_PORT}:8786
    depends_on:
      - nfs

  dask-worker:
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
    command: dask-worker ${MASTER_IP}:${DASKSCHEDULER_PORT} --local-directory=/dask-worker-space --nprocs=1  --nthreads=1 --memory-limit=40e8
    volumes:
      - ./app:/srv
      - ./store:/store

  front:
    build:
      context: ./front
      args:
        - http_proxy
        - https_proxy
    environment:
      - NODE_ENV=development
    command: npm run watch
    volumes:
      - ./front:/srv

  omniboard:
    build:
      context: ./front
      args:
        - http_proxy
        - https_proxy
    environment:
      - NODE_ENV=development
    command: npm run omniboard 
    volumes:
      - ./front:/srv
    ports:
      - "${OMNIBOARD_PORT}:9000"

  web:
    build:
      context: ./web
      args:
        - http_proxy
        - https_proxy
    volumes:
      - ./front/dist:/public/aplf
      - ./store:/public/store
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - front
      - dask-scheduler
      - tensorboard

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  app:
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    environment:
      - DASK_CONFIG=/srv/dask.config.yml
      - MASTER_IP
      - MONGO_PORT
    volumes:
      - ./app:/srv
      - ./store:/store
      - ./experiments:/experiments

  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    environment:
      - SHARED_DIRECTORY=/nfsshare
    privileged: true
    volumes:
      - ./:/nfsshare
    ports:
      - "2049:2049"


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
